version: '3.8'

services:
  app-dev:
    image: ghcr.io/clue355/azure_pipeline:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  app-prod:
    image: your_other_container_repo_here
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

